export const SOCKET_EVENT_CONNECT = 'connect';
export const SOCKET_EVENT_DISCONNECT = 'disconnect';
export const SOCKET_EVENT_CONNECT_ERROR = 'connect_error';
export const SOCKET_EVENT_FRIEND_REQUEST = 'SOCKET_EVENT_FRIEND_REQUEST';
export const SOCKET_EVENT_FRIEND_REQUEST_FINISH = 'SOCKET_EVENT_FRIEND_REQUEST_FINISH';
export const SOCKET_EVENT_FRIEND_REQUEST_RECEIVED = 'SOCKET_EVENT_FRIEND_REQUEST_RECEIVED';
export const SOCKET_EVENT_FRIEND_REQUEST_RECEIVED_FINISH =
  'SOCKET_EVENT_FRIEND_REQUEST_RECEIVED_FINISH';
export const SOCKET_EVENT_FRIEND_REQUEST_REJECT = 'SOCKET_EVENT_FRIEND_REQUEST_REJECT';
export const SOCKET_EVENT_FRIEND_REQUEST_REJECT_FINISH =
  'SOCKET_EVENT_FRIEND_REQUEST_REJECT_FINISH';
export const SOCKET_EVENT_DELETE_FRIEND = 'SOCKET_EVENT_DELETE_FRIEND';
export const SOCKET_EVENT_SENT_FRIEND_MESSAGE = 'SOCKET_EVENT_SENT_FRIEND_MESSAGE';
export const SOCKET_EVENT_SENT_FRIEND_MESSAGE_FINISH = 'SOCKET_EVENT_SENT_FRIEND_MESSAGE_FINISH';
export const SOCKET_EVENT_CREATE_GROUP = 'SOCKET_EVENT_CREATE_GROUP';
export const SOCKET_EVENT_CREATE_GROUP_FINISH = 'SOCKET_EVENT_CREATE_GROUP_FINISH';
export const SOCKET_EVENT_SEND_GROUP_MESSAGE = 'SOCKET_EVENT_SEND_GROUP_MESSAGE';
export const SOCKET_EVENT_SEND_GROUP_MESSAGE_FINISH = 'SOCKET_EVENT_SEND_GROUP_MESSAGE_FINISH';
export const SOCKET_EVENT_ADD_GROUP_MEMBERS = 'SOCKET_EVENT_ADD_GROUP_MEMBERS';
export const SOCKET_EVENT_DELETE_GROUP_MEMBERS = 'SOCKET_EVENT_DELETE_GROUP_MEMBERS';
export const SOCKET_EVENT_QUIT_GROUP = 'SOCKET_EVENT_QUIT_GROUP';
export const SOCKET_EVENT_DISBAND_GROUP = 'SOCKET_EVENT_DISBAND_GROUP';
export const SOCKET_EVENT_UPDATE_GROUP_NAME = 'SOCKET_EVENT_UPDATE_GROUP_NAME';
